common: &common
  hostname: localhost
  port: 8091
  username: Administrator
  password: '123456'
  pool: default

development:
  <<: *common
  bucket: videos

test:
  <<: *common
  bucket: videos
production:
  hostname: localhost
  port: 8091
  username: Administrator
  password: asd123!@#
  pool: default
  bucket: videos
